name: BijisSpace
main: fr.brangers.BijisSpace.Main
version: 1.0
api-version: 1.15
commands:
   rocket:
      description: Your description
      usage: /<command>
   fuel:
      description: Your description
      usage: /<command>